#!/bin/bash

# cmake -S ./ -B build/Release -DCMAKE_BUILD_TYPE=Release
# cmake --build build/Release
# ./build/Release/List

cmake -S ./ -B build/Debug -DCMAKE_BUILD_TYPE=Debug
cmake --build build/Debug
./build/Debug/List
